<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Helpdesk Ticket</title>
</head>

<body style="margin:0; padding:30px; background:#eef2f7; font-family:'Segoe UI', sans-serif;">

    <table width="650" cellpadding="0" cellspacing="0" 
           align="center"
           style="background:#fff; border-radius:16px; overflow:hidden;
                  box-shadow:0 10px 35px rgba(0,0,0,0.15);">

        <!-- Gradient Header -->
        <tr>
            <td style="padding:35px 20px; text-align:center;
                       background:linear-gradient(135deg, #4a90e2, #007bff);">
                <h1 style="margin:0; font-size:28px; color:#fff; font-weight:600;">
                    🔧 Technical Support Request
                </h1>
                <p style="color:#e3e9ff; margin-top:8px; font-size:14px;">
                    A new helpdesk ticket has been submitted
                </p>
            </td>
        </tr>

        <!-- Content Section -->
        <tr>
            <td style="padding:30px 40px;">

                <p style="font-size:16px; color:#333;">
                    Dear <strong>Technical Team</strong>,<br><br>
                    You have received a new helpdesk ticket. Review the information below:
                </p>

                <!-- Info Card -->
                <!-- Info Card -->
                <div style="margin-top:20px; padding:22px; 
                            background:#f7faff; 
                            border-radius:14px;
                            border:1px solid #dce6f9;
                            box-shadow:0 3px 8px rgba(0,0,0,0.05);">

                    <!-- Ticket No -->
                    <p style="margin:0; font-size:16px;">
                        <strong style="color:#1a3d7c;">🎟 Ticket No:</strong>
                        <span style="color:#007bff; font-weight:600; background:#e7f0ff;
                                    padding:4px 10px; border-radius:6px;">
                            {{ $ticket_no }}
                        </span>
                    </p>

                    <!-- Date -->
                    <p style="margin:10px 0 0; font-size:15px;">
                        <strong style="color:#1a3d7c;">📅 Date:</strong>
                        <span style="color:#333;">{{ $date }}</span>
                    </p>

                    <!-- Organization -->
                    <p style="margin:10px 0 0; font-size:15px;">
                        <strong style="color:#1a3d7c;">🏢 Organization:</strong>
                        <span style="color:#333;">{{ $organization }}</span>
                    </p>

                    <!-- Employee -->
                    <p style="margin:10px 0 0; font-size:15px;">
                        <strong style="color:#1a3d7c;">👤 Employee Name:</strong>
                        <span style="color:#333;">{{ $employee_name }}</span>
                    </p>

                    <!-- Email -->
                    <p style="margin:10px 0 0; font-size:15px;">
                        <strong style="color:#1a3d7c;">📩 Email:</strong>
                        <span style="color:#333;">{{ $email }}</span>
                    </p>

                    <!-- Message Box -->
                    <div style="margin-top:15px; padding:15px; 
                                background:#ffffff;
                                border-left:4px solid #007bff;
                                border-radius:10px;
                                box-shadow:0 2px 5px rgba(0,0,0,0.05);">
                        <strong style="color:#1a3d7c;">📝 Message:</strong><br>
                        <span style="color:#555; font-size:15px;">
                            {{ $message }}
                        </span>
                    </div>
                </div>


                <!-- Image Section -->
                @if($image)
                <h3 style="margin-top:35px; color:#1a3d7c; font-size:18px; font-weight:600;">
                    📎 Attached Screenshot / Image:
                </h3>

                <div style="padding:14px; background:#fafafa; 
                            border-radius:14px; 
                            border:1px solid #e3e3e3;
                            display:inline-block; 
                            box-shadow:0 4px 12px rgba(0,0,0,0.08);">
                    <img src="{{ $image }}" 
                         alt="Helpdesk Image"
                         style="max-width:550px; 
                                border-radius:10px; 
                                display:block;">
                </div>
                @endif

                <!-- Bottom Note -->
                {{-- <p style="margin-top:30px; font-size:13px; color:#666; text-align:center;">
                    This message was automatically generated by the Helpdesk System.
                </p> --}}

            </td>
        </tr>

        <!-- Footer -->
        <tr>
            <td style="background:#f0f4fa; padding:12px; text-align:center;">
                <p style="margin:0; font-size:12px; color:#666;">
                    © {{ date('Y') }} Swch — All Rights Reserved
                </p>
            </td>
        </tr>

    </table>

</body>
</html>
